#stages:
#  - test
#
#test:
#  stage: test
#  image: node:18.16.0 # Use an appropriate Node.js version
#  before_script:
#    - npm install
#  script:
#    - npm run test-mochawesome
#  artifacts:
#    paths:
#      - TestResults/NormalExecution # Artifacts for mochawesome reports

#parallel_test:
#  stage: test
#  image: node:14 # Use an appropriate Node.js version
#  before_script:
#    - npm install
#  script:
#    - npm run test-parallel-mochawesome
#  artifacts:
#    paths:
#      - TestResults/ParallelExecution # Artifacts for parallel execution reports
selenium_tests:
  image: node:18.16.0
  before_script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get update
    - apt-get -y install libnss3-dev
    - npm install chromedriver@116
    - npm install
    - chmod 0777 ./node_modules/.bin/mocha
    - chmod 0777 ./node_modules/chromedriver/bin/chromedriver
    - ./node_modules/chromedriver/bin/chromedriver&
  script:
    - echo "Current working directory: $PWD"
    - npm run test-mochawesome
  artifacts:
    paths:
      - TestResults/NormalExecution
