#stages:
#  - test
#
#test:
#  stage: test
#  image: node:18.16.0 # Use an appropriate Node.js version
#  before_script:
#    - npm install
#  script:
#    - npm run test-mochawesome
#  artifacts:
#    paths:
#      - TestResults/NormalExecution # Artifacts for mochawesome reports

#parallel_test:
#  stage: test
#  image: node:14 # Use an appropriate Node.js version
#  before_script:
#    - npm install
#  script:
#    - npm run test-parallel-mochawesome
#  artifacts:
#    paths:
#      - TestResults/ParallelExecution # Artifacts for parallel execution reports
#selenium_tests:
#  image: node:18.16.0
#  before_script:
#    - apt-get update
#    - apt-get -y install libnss3-dev
#    - npm install chromedriver@115
#    - npm install -g mocha mochawesome
#    - npm install
#  services:
#    - name: selenium/standalone-chrome:115.0
#  script:
#    - ls
#    - mocha Test/**/*.test.js
#  artifacts:
#    paths:
#      - TestResults/NormalExecution
